export { default as Navbar } from './Navbar/Nabvar.jsx';
export { default as Banner } from './Banner/Banner.jsx';
export { default as Testimonials } from './Testimonials/Testimonials.jsx';
export { default as Products } from './Products/Products.jsx';
export { default as RecyclingInfo } from './RecyclingInfo/RecyclingInfo.jsx';
export { default as ContactInfo } from './ContactInfo/ContactInfo.jsx';
export { default as Newsletter } from './Newsletter/Newsletter.jsx';
export { default as InstagramInfo } from './InstagramInfo/InstagramInfo.jsx';
export { default as Footer } from './Footer/Footer.jsx';
